### ISSUE TITLE
Please Rebuild for UE 5.3

### ISSUE THREAD

**Issue by brybalicious** [monsieurgustav/UE-OSC#93]
```
Running AutomationTool...
Using bundled DotNet SDK version: 6.0.302
Starting AutomationTool...
Parsing command line: BuildPlugin -plugin="D:\02_UNREAL PROJECTS\Mattaesthesia\Plugins\UE-OSC\UE-OSC.uplugin" -package="D:\02_UNREAL PROJECTS\RebuiltPlugins\UE-OSC"
Initializing script modules...
Total script module initialization time: 0.21 s.
Executing commands...
Copying 30 file(s) using max 64 thread(s)
Reading plugin from D:\02_UNREAL PROJECTS\RebuiltPlugins\UE-OSC\HostProject\Plugins\UE-OSC\UE-OSC.uplugin...
Building plugin for host platforms: Win64
Running: C:\Program Files\Epic Games\UE_5.3\Engine\Binaries\ThirdParty\DotNet\6.0.302\windows\dotnet.exe "C:\Program Files\Epic Games\UE_5.3\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.dll" UnrealEditor Win64 Development -Project="D:\02_UNREAL PROJECTS\RebuiltPlugins\UE-OSC\HostProject\HostProject.uproject" -plugin="D:\02_UNREAL PROJECTS\RebuiltPlugins\UE-OSC\HostProject\Plugins\UE-OSC\UE-OSC.uplugin" -noubtmakefiles -manifest="D:\02_UNREAL PROJECTS\RebuiltPlugins\UE-OSC\HostProject\Saved\Manifest-UnrealEditor-Win64-Development.xml" -nohotreload -log="C:\Users\rainshadow\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.3\UBT-UnrealEditor-Win64-Development.txt"
Log file: C:\Users\rainshadow\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.3\UBT-UnrealEditor-Win64-Development.txt
Compiled assembly file 'C:\Users\rainshadow\AppData\Local\UnrealEngine\Intermediate\Build\BuildRules\MarketplaceRules.dll' appears to be for a newer CLR version or is otherwise invalid.  Unreal Build Tool will try to recompile this assembly now.  (Exception: Could not load file or assembly 'C:\Users\rainshadow\AppData\Local\UnrealEngine\Intermediate\Build\BuildRules\MarketplaceRules.dll'. Format of the executable (.exe) or library (.dll) is invalid.)
C:\Program Files\Epic Games\UE_5.3\Engine\Plugins\Marketplace\RuntimeAudioImporterMetaSound\Source\RuntimeAudioImporterEditor\RuntimeAudioImporterEditor.Build.cs(5,14): error CS0101: The namespace '<global namespace>' already contains a definition for 'RuntimeAudioImporterEditor'
C:\Program Files\Epic Games\UE_5.3\Engine\Plugins\Marketplace\RuntimeAudioImporterMetaSound\Source\RuntimeAudioImporter\RuntimeAudioImporter.Build.cs(6,14): error CS0101: The namespace '<global namespace>' already contains a definition for 'RuntimeAudioImporter'
C:\Program Files\Epic Games\UE_5.3\Engine\Plugins\Marketplace\RuntimeAudioImporterMetaSound\Source\RuntimeAudioImporterEditor\RuntimeAudioImporterEditor.Build.cs(7,9): error CS0111: Type 'RuntimeAudioImporterEditor' already defines a member called 'RuntimeAudioImporterEditor' with the same parameter types
C:\Program Files\Epic Games\UE_5.3\Engine\Plugins\Marketplace\RuntimeAudioImporterMetaSound\Source\RuntimeAudioImporter\RuntimeAudioImporter.Build.cs(8,9): error CS0111: Type 'RuntimeAudioImporter' already defines a member called 'RuntimeAudioImporter' with the same parameter types
C:\Program Files\Epic Games\UE_5.3\Engine\Plugins\Marketplace\UIWS\Source\UIWS\UIWS.Build.cs(12,9): warning CS0618: 'ModuleRules.bEnforceIWYU' is obsolete: 'Deprecated in UE5.2 - Use IWYUSupport instead.'
C:\Program Files\Epic Games\UE_5.3\Engine\Plugins\Marketplace\Luminance\Source\Luminance\Luminance.Build.cs(10,25): warning CS0618: 'EngineIncludeOrderVersion.Unreal5_1' is obsolete: 'The Unreal 5.1 include order is deprecated and will be removed in 5.4.'
Total execution time: 2.52 seconds
Unhandled exception: System.ArgumentNullException: Value cannot be null. (Parameter 'element')
   at System.Attribute.GetCustomAttributes(MemberInfo element, Type attributeType, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](MemberInfo element)
   at UnrealBuildTool.ModuleRules.IsValidForTarget(Type ModuleType, ReadOnlyTargetRules TargetRules, String& InvalidReason) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\ModuleRules.cs:line 1623
   at UnrealBuildTool.UEBuildTarget.AddAllValidModulesToTarget(ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 3886
   at UnrealBuildTool.UEBuildTarget.PreBuildSetup(ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 3354
   at UnrealBuildTool.UEBuildTarget.Create(TargetDescriptor Descriptor, Boolean bSkipRulesCompile, Boolean bForceRulesCompile, Boolean bUsePrecompiled, UnrealIntermediateEnvironment IntermediateEnvironment, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 1366
   at UnrealBuildTool.BuildMode.CreateMakefileAsync(BuildConfiguration BuildConfiguration, TargetDescriptor TargetDescriptor, ISourceFileWorkingSet WorkingSet, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 1114
   at UnrealBuildTool.BuildMode.BuildAsync(List`1 TargetDescriptors, BuildConfiguration BuildConfiguration, ISourceFileWorkingSet WorkingSet, BuildOptions Options, FileReference WriteOutdatedActionsFile, ILogger Logger, Boolean bSkipPreBuildTargets) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 396
   at UnrealBuildTool.BuildMode.ExecuteAsync(CommandLineArguments Arguments, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 252
   at UnrealBuildTool.UnrealBuildTool.Main(String[] ArgumentsArray) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\UnrealBuildTool.cs:line 659
Took 2.63s to run dotnet.exe, ExitCode=6
UnrealBuildTool failed. See log for more details. (C:\Users\rainshadow\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.3\UBT-UnrealEditor-Win64-Development.txt)
AutomationTool executed for 0h 0m 3s
AutomationTool exiting with ExitCode=6 (6)
BUILD FAILED
```

**Comment by brybalicious** [comment]
There are now multiple versions of Runtime Audio Importer available on the Marketplace, including one built to support Metasounds. Please take care to include that plugin within your own plugin for the next release. Thanks!

**Comment by brybalicious** [comment]
After uninstalling Runtime Audio Importer and rebuilding the plugin:

```
Running AutomationTool...
Using bundled DotNet SDK version: 6.0.302
Starting AutomationTool...
Parsing command line: BuildPlugin -plugin="D:\02_UNREAL PROJECTS\Mattaesthesia\Plugins\UE-OSC\UE-OSC.uplugin" -package="D:\02_UNREAL PROJECTS\RebuiltPlugins\UE-OSC"
Initializing script modules...
Total script module initialization time: 0.17 s.
Executing commands...
Copying 30 file(s) using max 64 thread(s)
Reading plugin from D:\02_UNREAL PROJECTS\RebuiltPlugins\UE-OSC\HostProject\Plugins\UE-OSC\UE-OSC.uplugin...
Building plugin for host platforms: Win64
Running: C:\Program Files\Epic Games\UE_5.3\Engine\Binaries\ThirdParty\DotNet\6.0.302\windows\dotnet.exe "C:\Program Files\Epic Games\UE_5.3\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.dll" UnrealEditor Win64 Development -Project="D:\02_UNREAL PROJECTS\RebuiltPlugins\UE-OSC\HostProject\HostProject.uproject" -plugin="D:\02_UNREAL PROJECTS\RebuiltPlugins\UE-OSC\HostProject\Plugins\UE-OSC\UE-OSC.uplugin" -noubtmakefiles -manifest="D:\02_UNREAL PROJECTS\RebuiltPlugins\UE-OSC\HostProject\Saved\Manifest-UnrealEditor-Win64-Development.xml" -nohotreload -log="C:\Users\rainshadow\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.3\UBT-UnrealEditor-Win64-Development.txt"
Log file: C:\Users\rainshadow\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.3\UBT-UnrealEditor-Win64-Development.txt
C:\Program Files\Epic Games\UE_5.3\Engine\Plugins\Marketplace\Luminance\Source\Luminance\Luminance.Build.cs(10,25): warning CS0618: 'EngineIncludeOrderVersion.Unreal5_1' is obsolete: 'The Unreal 5.1 include order is deprecated and will be removed in 5.4.'
C:\Program Files\Epic Games\UE_5.3\Engine\Plugins\Marketplace\UIWS\Source\UIWS\UIWS.Build.cs(12,9): warning CS0618: 'ModuleRules.bEnforceIWYU' is obsolete: 'Deprecated in UE5.2 - Use IWYUSupport instead.'
Parsing headers for UnrealEditor
  Running Internal UnrealHeaderTool "D:\02_UNREAL PROJECTS\RebuiltPlugins\UE-OSC\HostProject\HostProject.uproject" "D:\02_UNREAL PROJECTS\RebuiltPlugins\UE-OSC\HostProject\Intermediate\Build\Win64\UnrealEditor\Development\UnrealEditor.uhtmanifest" -WarningsAsErrors -installed
Total of 16 written
Reflection code generated for UnrealEditor in 1.309391 seconds
Writing manifest to D:\02_UNREAL PROJECTS\RebuiltPlugins\UE-OSC\HostProject\Saved\Manifest-UnrealEditor-Win64-Development.xml
Building UnrealEditor...
Using Visual Studio 2022 14.36.32543 toolchain (C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532) and Windows 10.0.22621.0 SDK (C:\Program Files (x86)\Windows Kits\10).
Determining max actions to execute in parallel (12 physical cores, 24 logical cores)
  Executing up to 12 processes, one per physical core
  Requested 1.5 GB memory per action, 8.94 GB available: limiting max parallel actions to 5
------ Building 6 action(s) started ------
[1/6] Resource Default.rc2
[2/6] Compile [x64] SharedPCH.UnrealEd.Cpp20.cpp
[3/6] Compile [x64] Module.UE_OSC.cpp
D:\02_UNREAL PROJECTS\RebuiltPlugins\UE-OSC\HostProject\Plugins\UE-OSC\Source\UE_OSC\Private\Receive\oscpkt.hh(406): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
D:\02_UNREAL PROJECTS\RebuiltPlugins\UE-OSC\HostProject\Plugins\UE-OSC\Source\UE_OSC\Private\Receive\oscpkt.hh(431): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
D:\02_UNREAL PROJECTS\RebuiltPlugins\UE-OSC\HostProject\Plugins\UE-OSC\Source\UE_OSC\Private\Receive\oscpkt.hh(432): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
D:\02_UNREAL PROJECTS\RebuiltPlugins\UE-OSC\HostProject\Plugins\UE-OSC\Source\UE_OSC\Private\Receive\oscpkt.hh(587): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
D:\02_UNREAL PROJECTS\RebuiltPlugins\UE-OSC\HostProject\Plugins\UE-OSC\Source\UE_OSC\Private\Common\oscpack\osc\OscOutboundPacketStream.cpp(357): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
D:\02_UNREAL PROJECTS\RebuiltPlugins\UE-OSC\HostProject\Plugins\UE-OSC\Source\UE_OSC\Private\Common\oscpack\osc\OscOutboundPacketStream.cpp(635): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
D:\02_UNREAL PROJECTS\RebuiltPlugins\UE-OSC\HostProject\Plugins\UE-OSC\Source\UE_OSC\Private\Common\oscpack\osc\OscOutboundPacketStream.cpp(658): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
D:\02_UNREAL PROJECTS\RebuiltPlugins\UE-OSC\HostProject\Plugins\UE-OSC\Source\UE_OSC\Private\Receive\OscReceiverInputKey.cpp(16): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
[4/6] Link [x64] UnrealEditor-UE_OSC.lib
   Creating library D:\02_UNREAL PROJECTS\RebuiltPlugins\UE-OSC\HostProject\Plugins\UE-OSC\Intermediate\Build\Win64\x64\UnrealEditor\Development\UE_OSC\UnrealEditor-UE_OSC.lib and object D:\02_UNREAL PROJECTS\RebuiltPlugins\UE-OSC\HostProject\Plugins\UE-OSC\Intermediate\Build\Win64\x64\UnrealEditor\Development\UE_OSC\UnrealEditor-UE_OSC.exp
[5/6] Link [x64] UnrealEditor-UE_OSC.dll
   Creating library D:\02_UNREAL PROJECTS\RebuiltPlugins\UE-OSC\HostProject\Plugins\UE-OSC\Intermediate\Build\Win64\x64\UnrealEditor\Development\UE_OSC\UnrealEditor-UE_OSC.sup.lib and object D:\02_UNREAL PROJECTS\RebuiltPlugins\UE-OSC\HostProject\Plugins\UE-OSC\Intermediate\Build\Win64\x64\UnrealEditor\Development\UE_OSC\UnrealEditor-UE_OSC.sup.exp
[6/6] WriteMetadata UnrealEditor.target
Total time in Parallel executor: 30.90 seconds
Total execution time: 37.48 seconds
Took 37.58s to run dotnet.exe, ExitCode=0
Building plugin for target platforms: Android, IOS, Linux, LinuxArm64, Win64
Running: C:\Program Files\Epic Games\UE_5.3\Engine\Binaries\ThirdParty\DotNet\6.0.302\windows\dotnet.exe "C:\Program Files\Epic Games\UE_5.3\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.dll" UnrealGame Android Development -Project="D:\02_UNREAL PROJECTS\RebuiltPlugins\UE-OSC\HostProject\HostProject.uproject" -plugin="D:\02_UNREAL PROJECTS\RebuiltPlugins\UE-OSC\HostProject\Plugins\UE-OSC\UE-OSC.uplugin" -noubtmakefiles -manifest="D:\02_UNREAL PROJECTS\RebuiltPlugins\UE-OSC\HostProject\Saved\Manifest-UnrealGame-Android-Development.xml" -nohotreload -architecture=arm64 -log="C:\Users\rainshadow\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.3\UBT-UnrealGame-Android-Development.txt"
Log file: C:\Users\rainshadow\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.3\UBT-UnrealGame-Android-Development.txt
Total execution time: 0.43 seconds
Platform Android is not a valid platform to build. Check that the SDK is installed properly.
Took 0.52s to run dotnet.exe, ExitCode=6
UnrealBuildTool failed. See log for more details. (C:\Users\rainshadow\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.3\UBT-UnrealGame-Android-Development.txt)
AutomationTool executed for 0h 0m 38s
AutomationTool exiting with ExitCode=6 (6)
BUILD FAILED
```

**Comment by brybalicious** [comment]
Why is this targeting Android?

**Comment by brybalicious** [comment]
Hi Guillaume,

I suggest that it would be valuable to upload the built plugin for 5.3 as a release package :)

The plugin is not building on my side due to an issue building for Android:

```
Running AutomationTool...
Using bundled DotNet SDK version: 6.0.302
Starting AutomationTool...
Parsing command line: BuildPlugin -plugin=D:\02_UNREALPROJECTS\Mattaesthesia\Plugins\UE-OSC\UE-OSC.uplugin -package=D:\02_UNREALPROJECTS\RebuiltPlugins\UE-OSC
Initializing script modules...
Total script module initialization time: 0.17 s.
Executing commands...
Copying 65 file(s) using max 64 thread(s)
Reading plugin from D:\02_UNREALPROJECTS\RebuiltPlugins\UE-OSC\HostProject\Plugins\UE-OSC\UE-OSC.uplugin...
Building plugin for host platforms: Win64
Running: C:\Program Files\Epic Games\UE_5.3\Engine\Binaries\ThirdParty\DotNet\6.0.302\windows\dotnet.exe "C:\Program Files\Epic Games\UE_5.3\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.dll" UnrealEditor Win64 Development -Project="D:\02_UNREALPROJECTS\RebuiltPlugins\UE-OSC\HostProject\HostProject.uproject" -plugin="D:\02_UNREALPROJECTS\RebuiltPlugins\UE-OSC\HostProject\Plugins\UE-OSC\UE-OSC.uplugin" -noubtmakefiles -manifest="D:\02_UNREALPROJECTS\RebuiltPlugins\UE-OSC\HostProject\Saved\Manifest-UnrealEditor-Win64-Development.xml" -nohotreload -log="C:\Users\rainshadow\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.3\UBT-UnrealEditor-Win64-Development.txt"
Log file: C:\Users\rainshadow\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.3\UBT-UnrealEditor-Win64-Development.txt
Parsing headers for UnrealEditor
  Running Internal UnrealHeaderTool D:\02_UNREALPROJECTS\RebuiltPlugins\UE-OSC\HostProject\HostProject.uproject D:\02_UNREALPROJECTS\RebuiltPlugins\UE-OSC\HostProject\Intermediate\Build\Win64\UnrealEditor\Development\UnrealEditor.uhtmanifest -WarningsAsErrors -installed
Total of 16 written
Reflection code generated for UnrealEditor in 1.487942 seconds
Writing manifest to D:\02_UNREALPROJECTS\RebuiltPlugins\UE-OSC\HostProject\Saved\Manifest-UnrealEditor-Win64-Development.xml
Building UnrealEditor...
Using Visual Studio 2022 14.36.32544 toolchain (C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532) and Windows 10.0.22621.0 SDK (C:\Program Files (x86)\Windows Kits\10).
Determining max actions to execute in parallel (12 physical cores, 24 logical cores)
  Executing up to 12 processes, one per physical core
------ Building 6 action(s) started ------
[1/6] Resource Default.rc2
[2/6] Compile [x64] SharedPCH.UnrealEd.Cpp20.cpp
[3/6] Compile [x64] Module.UE_OSC.cpp
D:\02_UNREALPROJECTS\RebuiltPlugins\UE-OSC\HostProject\Plugins\UE-OSC\Source\UE_OSC\Private\Receive\oscpkt.hh(406): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
D:\02_UNREALPROJECTS\RebuiltPlugins\UE-OSC\HostProject\Plugins\UE-OSC\Source\UE_OSC\Private\Receive\oscpkt.hh(431): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
D:\02_UNREALPROJECTS\RebuiltPlugins\UE-OSC\HostProject\Plugins\UE-OSC\Source\UE_OSC\Private\Receive\oscpkt.hh(432): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
D:\02_UNREALPROJECTS\RebuiltPlugins\UE-OSC\HostProject\Plugins\UE-OSC\Source\UE_OSC\Private\Receive\oscpkt.hh(587): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
D:\02_UNREALPROJECTS\RebuiltPlugins\UE-OSC\HostProject\Plugins\UE-OSC\Source\UE_OSC\Private\Common\oscpack\osc\OscOutboundPacketStream.cpp(357): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
D:\02_UNREALPROJECTS\RebuiltPlugins\UE-OSC\HostProject\Plugins\UE-OSC\Source\UE_OSC\Private\Common\oscpack\osc\OscOutboundPacketStream.cpp(635): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
D:\02_UNREALPROJECTS\RebuiltPlugins\UE-OSC\HostProject\Plugins\UE-OSC\Source\UE_OSC\Private\Common\oscpack\osc\OscOutboundPacketStream.cpp(658): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
D:\02_UNREALPROJECTS\RebuiltPlugins\UE-OSC\HostProject\Plugins\UE-OSC\Source\UE_OSC\Private\Receive\OscReceiverInputKey.cpp(16): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
[4/6] Link [x64] UnrealEditor-UE_OSC.lib
   Creating library D:\02_UNREALPROJECTS\RebuiltPlugins\UE-OSC\HostProject\Plugins\UE-OSC\Intermediate\Build\Win64\x64\UnrealEditor\Development\UE_OSC\UnrealEditor-UE_OSC.lib and object D:\02_UNREALPROJECTS\RebuiltPlugins\UE-OSC\HostProject\Plugins\UE-OSC\Intermediate\Build\Win64\x64\UnrealEditor\Development\UE_OSC\UnrealEditor-UE_OSC.exp
[5/6] Link [x64] UnrealEditor-UE_OSC.dll
   Creating library D:\02_UNREALPROJECTS\RebuiltPlugins\UE-OSC\HostProject\Plugins\UE-OSC\Intermediate\Build\Win64\x64\UnrealEditor\Development\UE_OSC\UnrealEditor-UE_OSC.sup.lib and object D:\02_UNREALPROJECTS\RebuiltPlugins\UE-OSC\HostProject\Plugins\UE-OSC\Intermediate\Build\Win64\x64\UnrealEditor\Development\UE_OSC\UnrealEditor-UE_OSC.sup.exp
[6/6] WriteMetadata UnrealEditor.target
Total time in Parallel executor: 28.16 seconds
Total execution time: 33.96 seconds
Took 34.05s to run dotnet.exe, ExitCode=0
Building plugin for target platforms: Android, IOS, Linux, LinuxArm64, Win64
Running: C:\Program Files\Epic Games\UE_5.3\Engine\Binaries\ThirdParty\DotNet\6.0.302\windows\dotnet.exe "C:\Program Files\Epic Games\UE_5.3\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.dll" UnrealGame Android Development -Project="D:\02_UNREALPROJECTS\RebuiltPlugins\UE-OSC\HostProject\HostProject.uproject" -plugin="D:\02_UNREALPROJECTS\RebuiltPlugins\UE-OSC\HostProject\Plugins\UE-OSC\UE-OSC.uplugin" -noubtmakefiles -manifest="D:\02_UNREALPROJECTS\RebuiltPlugins\UE-OSC\HostProject\Saved\Manifest-UnrealGame-Android-Development.xml" -nohotreload -architecture=arm64 -log="C:\Users\rainshadow\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.3\UBT-UnrealGame-Android-Development.txt"
Log file: C:\Users\rainshadow\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.3\UBT-UnrealGame-Android-Development.txt
Android (8490178, based on r450784d) clang version 14.0.6 (https://android.googlesource.com/toolchain/llvm-project 4c603efb0cca074e9238af8b4106c30add4418f6)
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: C:/Users/rainshadow/AppData/Local/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/bin
Compiling with ray tracing enabled
Android (8490178, based on r450784d) clang version 14.0.6 (https://android.googlesource.com/toolchain/llvm-project 4c603efb0cca074e9238af8b4106c30add4418f6)
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: C:/Users/rainshadow/AppData/Local/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/bin
NDK toolchain: r25b, NDK version: 250200, ClangVersion: 14.0.6
Parsing headers for UnrealGame
  Running Internal UnrealHeaderTool D:\02_UNREALPROJECTS\RebuiltPlugins\UE-OSC\HostProject\HostProject.uproject D:\02_UNREALPROJECTS\RebuiltPlugins\UE-OSC\HostProject\Intermediate\Build\Android\UnrealGame\Development\UnrealGame.uhtmanifest -WarningsAsErrors -installed
Total of 16 written
Reflection code generated for UnrealGame in 0.6893187 seconds
Compiling Native 64-bit code with NDK API 'android-26'
Writing manifest to D:\02_UNREALPROJECTS\RebuiltPlugins\UE-OSC\HostProject\Saved\Manifest-UnrealGame-Android-Development.xml
Building UnrealGame...
Determining max actions to execute in parallel (12 physical cores, 24 logical cores)
  Executing up to 12 processes, one per physical core
------ Building 1 action(s) started ------
[1/1] Compile [arm64] Module.UE_OSC.cpp
In file included from D:/02_UNREALPROJECTS/RebuiltPlugins/UE-OSC/HostProject/Plugins/UE-OSC/Intermediate/Build/Android/a/UnrealGame/Development/UE_OSC/Module.UE_OSC.cpp:4:
In file included from D:/02_UNREALPROJECTS/RebuiltPlugins/UE-OSC/HostProject/Plugins/UE-OSC/Intermediate/Build/Android/UnrealGame/Inc/UE_OSC/UHT/OscFunctionLibrary.gen.cpp:8:
D:/02_UNREALPROJECTS/RebuiltPlugins/UE-OSC/HostProject/Plugins/UE-OSC/Source/UE_OSC/Public/Common/OscFunctionLibrary.h(28,32): error: '/*' within block comment [-Werror,-Wcomment]
     * - Path=/foo/bar Pattern=/* => Return=false
                               ^
D:/02_UNREALPROJECTS/RebuiltPlugins/UE-OSC/HostProject/Plugins/UE-OSC/Source/UE_OSC/Public/Common/OscFunctionLibrary.h(30,32): error: '/*' within block comment [-Werror,-Wcomment]
     * - Path=/foo/bar Pattern=/*\/bar => Return=true PatternRest=None
                               ^
D:/02_UNREALPROJECTS/RebuiltPlugins/UE-OSC/HostProject/Plugins/UE-OSC/Source/UE_OSC/Public/Common/OscFunctionLibrary.h(31,32): error: '/*' within block comment [-Werror,-Wcomment]
     * - Path=/foo/bar Pattern=/*\/bar/value => Return=true PatternRest=/value
                               ^
3 errors generated.
Total time in Parallel executor: 4.30 seconds
Total execution time: 6.41 seconds
Took 6.49s to run dotnet.exe, ExitCode=6
UnrealBuildTool failed. See log for more details. (C:\Users\rainshadow\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.3\UBT-UnrealGame-Android-Development.txt)
AutomationTool executed for 0h 0m 41s
AutomationTool exiting with ExitCode=6 (6)
BUILD FAILED
```

**Comment by brybalicious** [comment]
Originally the issue with building was because I already had a (conflicting) version of Runtime Audio Importer installed in my Engine plugins

**Comment by brybalicious** [comment]
It builds for Windows at least

**Comment by brybalicious** [comment]
Yes thanks. It is stupid! 😅 It builds for Android successfully now too.
iOS difficult since you need a Mac computer involved when compiling C++ (remote compilation).
